[project]
name = "pynotepad"
version = "0.1.0"
description = "Clon del bloc de notas escrito en Python"
readme = "README.md"
requires-python = ">=3.14"

authors = [
    { name = "Martín Ariza", email="martin.ariza.camargo@gmail.com"}
]

keywords = ["Python","Software","Notepad","Bloc de notas","GUI","Tkinter"]

dependencies = [
    "mypy>=2.1.0",
    "pytest>=9.0.3",
    "ruff>=0.15.15",
]

[tool.ruff]
target-version = "py311"
line-length    = 88
exclude = [
    ".git", ".venv", "__pycache__",
    "*.pyi", "build", "dist",
    "migrations", "alembic/versions",
]